### ISSUE TITLE
Different output with -w

### ISSUE THREAD

**Issue by ilyalyo** [mcandre/cowl#6]
Cowl doesn't process some files without -w option
Example:
without -w option
![img](https://i.gyazo.com/7694d602d9d2c2a7cda89a0af12e2fd4.png)
with -w 80 (default value)
![img](https://i.gyazo.com/57bee2028d3772d385162307ac002d26.png)

**Comment by mcandre** [comment]
Some of the example files are designed to pass linting, to test that the linter does the right thing (skip) when reading a file that should have no warnings.

If you think cowl is processing a file incorrectly, please give more information.

Please don't upload softwre logs as screenshots. Whenever possible, copy and paste the raw text into your report. This allows the logs to be searchable, so that other users may find your report more easily.

On GitHub, surround log snippets with triple backticks, as described in https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
